/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.mvpigs.pigcoin;

import org.junit.Test;

import java.security.KeyPair;

import static org.junit.Assert.*;

public class WalletTest {

    @Test
    public void setygetAddressTest() {
        Wallet wallet = new Wallet();
        KeyPair pair = GenSig.generateKeyPair();
        wallet.setAddress(pair.getPublic());
        assertEquals(pair.getPublic(), wallet.getAddress());
    }

    @Test
    public void setygetSKeyTest() {
        Wallet wallet = new Wallet();
        KeyPair pair = GenSig.generateKeyPair();
        wallet.setSK(pair.getPrivate());
        assertEquals(pair.getPrivate(), wallet.getSKey());
    }

    /**
    @Test
    public void generateKeyPairTest() {
        Wallet wallet = new Wallet();
        wallet.generateKeyPair();
        wallet.setAddress(wallet.getAddress());
        wallet.setSK(wallet.getSKey());
    }*/
}
