/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.mvpigs.pigcoin;

import org.junit.Test;

import java.security.KeyPair;

import static org.junit.Assert.*;

public class WalletTest {

    @Test
    public void setygetAddressTest() {
        Wallet wallet = new Wallet();
        KeyPair pair = GenSig.generateKeyPair();
        wallet.setAddress(pair.getPublic());
        assertEquals(pair.getPublic(), wallet.getAddress());
    }
}
